### PR TITLE
Update to v4 authentication

### PR DESCRIPTION
**Pull request by TheSinding**
### Summary

This solves the problem with feathers-authentication v4

### CODE REVIEW

**Comment by claustres** [comment]
I am just coming into the module since @eddyystop needed to stop his contribution, it will probably need some time to see how it goes but the idea is to still releasing when necessary. 

To merge this one I would need a more detailed explanation of the broad lines: why exactly this PR is required to use the module in v4 as it seems to also work as is ? What are the additional features ?

By the way I've seen https://www.npmjs.com/package/authentication-local-management-v4, which seems to be a release of your fork with some additional features but we don't have any PR for. Are you aware of it ?

Thanks for your feedback

**Comment by TheSinding** [comment]
Its been 5 months since I looked at it and I'm on vacation right now, can it wait till I get back?

I don't really remember it

**Comment by claustres** [comment]
Of course this can wait we only try to get on with this module and to keep it up to date, I don't yet have any ETA for a release ;-)

**Comment by gchokeen** [comment]
Are you going to merge it anytime sooner?

**Comment by TheSinding** [comment]
So I've taken a look at the pull request again.

It basically just makes the library work with the new `hash-password` method/hook from the newer [feathers/authentication-local](https://github.com/feathersjs/feathers/blob/master/packages/authentication-local) library. Specifically [this](https://github.com/feathersjs/feathers/blob/master/packages/authentication-local/src/hooks/hash-password.ts#L16-L19) part of the `hash-password` method. 

It just adds the "support" for the new `field` parameter.
Then there is a lot of `prettier` changes, which should properly be reversed, to make it look like the old code again.

Then I fix the tests.

I don't know why it would work as-is for some people, when I tested it (and use it in production), it broke with v4.

There are no new features in this branch, it just keeps the library as-is, but I wouldn't mind working on it.

**Comment by claustres** [comment]
OK thanks, just tried to merge by resolving conflicts but CI fails, will need a deeper look.

**Comment by TheSinding** [comment]
I will take a look later

**Comment by claustres** [comment]
I've resolve the issue with the lock file locally and pushed to master, thanks very much.

**Comment by TheSinding** [comment]
You got it, if you need any help, just ask :)

**Pull request merged**
