### PR TITLE
chore(): update feathers libs

### PR DESCRIPTION
**Pull request by bitflower**
Update all feathers libs to latest 3.x

Tests have passed.

Also fixed 'package.json' to be able to install from GitHub.

### CODE REVIEW

**Comment by bitflower** [comment]
Hey guys, would appreciate a review ;-)

**Comment by bitflower** [comment]
Hi guys, would be cool to have some progress here! I'm running into it over and over again and always need to fix locally...

**Comment by bitflower** [comment]
Awesome, thanks. Just recently felt the urge to solve this once and for all.

Are you planning a release?

**Comment by claustres** [comment]
I am just coming into the module since @eddyystop needed to stop his contribution, will probably need some time to see how it goes but yes the idea is to still releasing when necessary. However I don't yet have any ETA.

**Pull request merged**
