### PR TITLE
migrate to featchers-common-hooks v4

### PR DESCRIPTION
**Pull request by Anton-Nikishkin**
### Summary
- [X] Tell us about the problem your pull request is solving.
Remove deprecation dependency warnings.
- [X] Are there any open issues that are related to this?
#94 
- [X] Is this PR dependent on PRs in other repos?
No

### CODE REVIEW

**Comment by eddyystop** [comment]
Thank you.

**Comment by Sicria** [comment]
Could you please release a new version where this is included, still receiving these warnings on ``@2.0.0``.

**Comment by eddyystop** [comment]
I'll have to look at why the tests are failing.

**Comment by eddyystop** [comment]
I pushed a commit directly to the master branch bumping feathers-hooks-common to ^4.14.1 . Published as v2.0..1.

This was not done as a PR because the tests now fail and I don't see how to fix them without a rewrite. Basically some of the .then() are still suspended when Mocha gets control from the test. They only continue to run after the Mocha test timesout.

This'll have to wait until the rewrite planned for this repo.

**Pull request merged**
