### PR TITLE
Add serviceParams option

### PR DESCRIPTION
**Pull request by vonagam**
Ability to pass params to users service. Use case described in #107.
Also moved `patchUser` to helper.

### CODE REVIEW

**Comment by eddyystop** [comment]
I'm planning to rewrite this repo this year. async/await instead of promises, prop values compatible with all DBs, etc.

I'll consider all outstanding issues at that point.

Options will include functions for overriding all service calls made by the repo. This is something we learned with feathers-hooks-common, e.g. fastJoin instead of populate.

**Comment by vonagam** [comment]
Sounds good. Hope it will be sooner, than later.
I'll close pull request then.

**Comment by eddyystop** [comment]
Its a matter of there being a lot to do:
- stabilize feathers-plus/cli (10 months so far)
- finish softDelete2 for common hooks & document (1 week)
- start feathers-plus/testing-patterns
- add softDelete2 to feathers-plus/cli
- document consistent way to handle semaphores in hooks
- convert common hooks to above and add utility functions for semaphores
- feathers-authentication-management rewrite
- add feathers-authentication-management to feathers-plus/cli

**Comment by vonagam** [comment]
I am not blocked by this issue, no rush.

Thanks for clarification and your work.

**Pull request closed without merging**
